package Bharat.RecommendationPrograms;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.RandomAccessFile;

public class Yelp {

	public static void main(String[] args) throws Exception {

		BufferedReader br = new BufferedReader(
				new FileReader(
						"D:\\Data Sets\\yelp_phoenix_academic_dataset\\yelp_academic_dataset_review.json"));
		/*BufferedWriter bw = new BufferedWriter(
				new FileWriter(
						"D:\\Data Sets\\yelp_phoenix_academic_dataset\\yelp_academic_dataset_checkin_array.json"));*/
		/*BufferedReader br = new BufferedReader(
				new FileReader(
						"D:\\Data Sets\\yelp_phoenix_academic_dataset\\source.txt"));*/
		/*BufferedWriter bw = new BufferedWriter(
				new FileWriter(
						"D:\\Data Sets\\yelp_phoenix_academic_dataset\\dest.txt"));
		*/
		String arrayTag="[";
		//bw.write(arrayTag);
		
		String line;
		try {
			while ((line = br.readLine()) != null) {
				System.out.println(line);
			}
			
		} catch (Exception e) {

			e.printStackTrace();
		} finally {

			br.close();
			//bw.close();
		}

		/*
		 * JSONParser parser = new JSONParser();
		 * 
		 * try {
		 * 
		 * Object obj = parser.parse(new FileReader(
		 * "D:\\Data Sets\\yelp_phoenix_academic_dataset\\yelp_academic_dataset_checkin.json"
		 * ));
		 * 
		 * JSONObject jsonObject = (JSONObject) obj;
		 * 
		 * String name = (String) jsonObject.get("business_id");
		 * System.out.println(name);
		 * 
		 * long age = (Long) jsonObject.get("name"); System.out.println(age);
		 * 
		 * // loop array JSONArray msg = (JSONArray)
		 * jsonObject.get("neighborhoods"); Iterator<String> iterator =
		 * msg.iterator(); while (iterator.hasNext()) {
		 * System.out.println(iterator.next()); }
		 * 
		 * } catch (FileNotFoundException e) { e.printStackTrace(); } catch
		 * (IOException e) { e.printStackTrace(); } catch (ParseException e) {
		 * e.printStackTrace(); }
		 */
	}

}
/*{
  "status": "OK",
  "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
  "url": "",
  "language": "english",
  "text": "An oasis of little kid fun in Phoenix, we hadn't been in over a year and came for a birthday party.  They're always running a deal, so look for one before departing.  One year we did an annual pass.  It was a good deal.  There are also lots of special events that include deals.  One time we met spiderman.\\n\\nThere are lots of rides, mostly for shorter kids.  Some have modest height requirement that exclude the very young and some that exclude the tall.  There's a train, carousel, mini-coaster, tea cup ride, an up and down parachute ride, several rides that go in circles in different vehicles (e.g., planes, cars, and helicopters and futuristic flying machines), and a bumper boats ride that turns into a splash pad in the summer.  Determining whether the adults need a wrist band or tickets is always a little tricky as adults are needed on some rides, but not others, and it also depends on the age of the child.  The place has a little bit of a rundown feel, but kids don't notice and have loads of fun.  The arcade is really rundown, but the ATM is really nice.  There isn't much shade, so be prepared.  All of the staff are really nice.\\n\\nThere are usually a few game and art vendors about: ball toss game, sand art, and/or face painting.  All are a big hit with the kids, but also hit up the wallet for a few bucks a piece.  Everyone is a winner at ball toss, by the way.",
  "entities": [
    {
      "type": "City",
      "relevance": "0.796433",
      "sentiment": {
        "type": "positive",
        "score": "0.349374",
        "mixed": "1"
      },
      "count": "1",
      "text": "Phoenix",
      "disambiguated": {
        "subType": [
          "PlaceWithNeighborhoods"
        ],
        "name": "Phoenix, Arizona",
        "website": "http://www.phoenix.gov/",
        "dbpedia": "http://dbpedia.org/resource/Phoenix,_Arizona",
        "freebase": "http://rdf.freebase.com/ns/m.0d35y",
        "geonames": "http://sws.geonames.org/5308655/",
        "census": "http://www.rdfabout.com/rdf/usgov/geo/us/az/counties/maricopa_county/phoenix",
        "yago": "http://yago-knowledge.org/resource/Phoenix,_Arizona"
      }
    }
  ]
}
------------------------------------------------------------------------------------------------------------------------------
{
  "status": "OK",
  "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
  "url": "",
  "language": "english",
  "text": "This restaurant = a great experience. Everything about this place is fabulous. The server was extremely attentive, the food was fresh and delicious, and the intimate yet casual ambiance is to die for.\\n\\nENTREE\\n\\nFor starters, they do put a rather unique spin on the typical 'chips and salsa' that's brought out to you in the beginning of most Spanish restaurants. They bake corn tortillas until their crisp and serve that with an interesting array of dips: black bean, salsa, and a tray of salt, limes, and hot sauce to stir in.\\n\\nI ordered a simple entree of carne asada tacos and black beans; my meal was yummy and filling, and I even had leftovers. Beware of spicy when choosing your dish, however. My coworker kept complaining about how hot her meal was (beer battered fish burrito). I don't know if she has sensitive taste buds, or if it was really spicy.. so proceed with caution.\\n\\nDESSERT\\n\\nThey have a wide variety of entrees, but unfortunately only have 3 sweet options. I'm a BIG dessert person, so it was a little disappointing but what the heck. I ordered the flan and it was scrumptious, incredible, delectable, etc.. all that good stuff. My coworker who complained about the spiciness called our dessert 'sexy'. So I guess sexy is the best way to describe it's caramel drizzle and chocolate bark yumminess.\\n\\nAMBIANCE/SERVICE\\n\\nThe waiter was incredibly attentive and friendly. He answered all questions we had, and gave speedy and praiseworthy service. The manager even came up to our table and made conversation; that, to me, is always a plus. The background music helped add to the overall appeal to the restaurant. \\n\\nI would definitely go back to SOL. Maybe tomorrow..",
  "entities": [
    {
      "type": "FieldTerminology",
      "relevance": "0.907827",
      "sentiment": {
        "type": "positive",
        "score": "0.0394731",
        "mixed": "1"
      },
      "count": "1",
      "text": "chips and salsa"
    }
  ]
}
------------------------------------------------------------------------------------------------------------------------------------------------------
{
  "status": "OK",
  "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
  "url": "",
  "language": "english",
  "text": "Yeah...notsomuch.\\n\\nSprinkles is sooooooooo not worth the wait . Or the chaos. Or the hype. Or the attitude from the morons who work there. Other things that are terrible about Sprinkles include...\\n\\n- The cupcakes are not that great. I ordered two. The vanilla was okay, the cinnamon was dry and chalky and I really disliked it.\\n\\n- This place is a disorganized mess. \\n\\n- There is no rhyme or reason to any of the ordering process. My friends and I were carefully watching the ordering process and we actually think they decided to choose the dumbest and most irrational methods to take orders and dispense cupcakes. Just stupid.\\n\\n- The owners must have purposely only hired people who cannot think for themselves or make decisions. No sane person could possibly work here without being like \\\"um...there might be a better way to do this...\\\"\\n\\n- Also, the employees were rude. Did I mention dumb?\\n\\nSo get this: I attempted to order a bottle of water. I told the clerk it's 100  degrees outside, I walked there and I'm realllllllly thirsty. The idiot at the counter told me \\\"You can order a water here but you must wait for your name to be called to receive the water and pay for it.\\\" I pointed out that the water was RIGHT THERE and there wasn't anyone currently paying or using the register. Couldn't she just sell me a water? She said \\\"NO\\\" and proceeded to WRITE DOWN MY ORDER (just the word \\\"water\\\") on a cupcake order slip. She then told me to stand there and wait for my name to be called so she could HAND ME THE WATER and then ring me up.\\n\\nI was all sorts of thirsty and all sorts of moody that day so I got really ghetto on her ass and was all like OH HELLLLLL-TO-THE-NO!\\\" \\n\\nI said \\\"It's quite simple. Just hand me the water and I will hand you money. End of discussion.\\\" (There are the actual words out of the mouth!)\\n\\nShe looked really mad and also possibly terrified of me and my 5'4\\\" 110 lbs of fury. Thankfully she handed me my water so I did not have to stab her. Which was good because I was waaaaaaaaay too thirsty to stab anyone. \\n\\nI must be properly hydrated in order to commit crimes of passion. And I'm mad crazy passionate about my cupcakes, yo.",
  "keywords": [
    {
      "text": "water",
      "relevance": "0.927851",
      "sentiment": {
        "type": "positive",
        "score": "0.0252377"
      }
    },
    {
      "text": "cupcake order slip",
      "relevance": "0.855319",
      "sentiment": {
        "type": "negative",
        "score": "-0.0510724"
      }
    },
    {
      "text": "dispense cupcakes",
      "relevance": "0.683236",
      "sentiment": {
        "type": "negative",
        "score": "-0.245383"
      }
    },
    {
      "text": "disorganized mess",
      "relevance": "0.635529",
      "sentiment": {
        "type": "negative",
        "score": "-0.360601"
      }
    },
    {
      "text": "irrational methods",
      "relevance": "0.606805",
      "sentiment": {
        "type": "negative",
        "score": "-0.28616"
      }
    },
    {
      "text": "sane person",
      "relevance": "0.588753",
      "sentiment": {
        "type": "negative",
        "score": "-0.271177"
      }
    },
    {
      "text": "better way",
      "relevance": "0.58279",
      "sentiment": {
        "type": "positive",
        "score": "0.302429"
      }
    },
    {
      "text": "OH HELLLLLL-TO-THE-NO",
      "relevance": "0.550502",
      "sentiment": {
        "type": "negative",
        "score": "-0.544736"
      }
    },
    {
      "text": "actual words",
      "relevance": "0.54839",
      "sentiment": {
        "type": "negative",
        "score": "-0.293866"
      }
    },
    {
      "text": "process",
      "relevance": "0.368205",
      "sentiment": {
        "type": "positive",
        "score": "0.0297091"
      }
    },
    {
      "text": "sorts",
      "relevance": "0.352449",
      "sentiment": {
        "type": "negative",
        "score": "-0.238009"
      }
    },
    {
      "text": "wait",
      "relevance": "0.331771",
      "sentiment": {
        "type": "negative",
        "score": "-0.320574"
      }
    },
    {
      "text": "morons",
      "relevance": "0.315561",
      "sentiment": {
        "type": "negative",
        "score": "-0.121249"
      }
    },
    {
      "text": "Sprinkles",
      "relevance": "0.31242",
      "sentiment": {
        "type": "negative",
        "score": "-0.31656"
      }
    },
    {
      "text": "hype",
      "relevance": "0.302426",
      "sentiment": {
        "type": "neutral"
      }
    },
    {
      "text": "rhyme",
      "relevance": "0.29324",
      "sentiment": {
        "type": "negative",
        "score": "-4.59886e-05"
      }
    },
    {
      "text": "notsomuch.\\n\\nSprinkles",
      "relevance": "0.291634",
      "sentiment": {
        "type": "negative",
        "score": "-0.22135"
      }
    },
    {
      "text": "clerk",
      "relevance": "0.290399",
      "sentiment": {
        "type": "neutral"
      }
    },
    {
      "text": "chaos",
      "relevance": "0.289535",
      "sentiment": {
        "type": "negative",
        "score": "-0.473794"
      }
    },
    {
      "text": "cinnamon",
      "relevance": "0.288687",
      "sentiment": {
        "type": "negative",
        "score": "-0.21989"
      }
    },
    {
      "text": "attitude",
      "relevance": "0.28716",
      "sentiment": {
        "type": "negative",
        "score": "-0.117875"
      }
    },
    {
      "text": "vanilla",
      "relevance": "0.285359",
      "sentiment": {
        "type": "negative",
        "score": "-0.000632291"
      }
    },
    {
      "text": "idiot",
      "relevance": "0.284382",
      "sentiment": {
        "type": "negative",
        "score": "-0.0219106"
      }
    },
    {
      "text": "things",
      "relevance": "0.283278",
      "sentiment": {
        "type": "negative",
        "score": "-0.407277"
      }
    },
    {
      "text": "um",
      "relevance": "0.281874",
      "sentiment": {
        "type": "positive",
        "score": "0.210569"
      }
    },
    {
      "text": "ghetto",
      "relevance": "0.281765",
      "sentiment": {
        "type": "negative",
        "score": "-0.257435"
      }
    },
    {
      "text": "reason",
      "relevance": "0.281406",
      "sentiment": {
        "type": "negative",
        "score": "-4.48781e-05"
      }
    },
    {
      "text": "yo",
      "relevance": "0.281307",
      "sentiment": {
        "type": "negative",
        "score": "-0.135189"
      }
    },
    {
      "text": "owners",
      "relevance": "0.27974",
      "sentiment": {
        "type": "positive",
        "score": "0.00501101"
      }
    },
    {
      "text": "bottle",
      "relevance": "0.279631",
      "sentiment": {
        "type": "negative",
        "score": "-0.18791"
      }
    },
    {
      "text": "people",
      "relevance": "0.279629",
      "sentiment": {
        "type": "positive",
        "score": "0.00501101"
      }
    },
    {
      "text": "place",
      "relevance": "0.279285",
      "sentiment": {
        "type": "negative",
        "score": "-0.321457"
      }
    },
    {
      "text": "ass",
      "relevance": "0.278384",
      "sentiment": {
        "type": "negative",
        "score": "-0.286552"
      }
    },
    {
      "text": "friends",
      "relevance": "0.278196",
      "sentiment": {
        "type": "positive",
        "score": "0.20722"
      }
    },
    {
      "text": "lbs",
      "relevance": "0.277386",
      "sentiment": {
        "type": "negative",
        "score": "-0.312683"
      }
    },
    {
      "text": "decisions",
      "relevance": "0.276846",
      "sentiment": {
        "type": "neutral"
      }
    },
    {
      "text": "employees",
      "relevance": "0.276055",
      "sentiment": {
        "type": "negative",
        "score": "-0.232448"
      }
    },
    {
      "text": "money",
      "relevance": "0.273781",
      "sentiment": {
        "type": "neutral"
      }
    },
    {
      "text": "RIGHT",
      "relevance": "0.273564",
      "sentiment": {
        "type": "positive",
        "score": "0.15276"
      }
    },
    {
      "text": "degrees",
      "relevance": "0.273283",
      "sentiment": {
        "type": "negative",
        "score": "-0.0538902"
      }
    },
    {
      "text": "moody",
      "relevance": "0.273217",
      "sentiment": {
        "type": "negative",
        "score": "-0.36371"
      }
    },
    {
      "text": "counter",
      "relevance": "0.272827",
      "sentiment": {
        "type": "negative",
        "score": "-0.0213815"
      }
    },
    {
      "text": "orders",
      "relevance": "0.272781",
      "sentiment": {
        "type": "negative",
        "score": "-0.302656"
      }
    },
    {
      "text": "crimes",
      "relevance": "0.272613",
      "sentiment": {
        "type": "positive",
        "score": "0.0180845"
      }
    },
    {
      "text": "fury",
      "relevance": "0.272566",
      "sentiment": {
        "type": "negative",
        "score": "-0.274935"
      }
    },
    {
      "text": "NO\\",
      "relevance": "0.272412",
      "sentiment": {
        "type": "negative",
        "score": "-0.000487806"
      }
    },
    {
      "text": "water\\",
      "relevance": "0.272149",
      "sentiment": {
        "type": "negative",
        "score": "-0.0172919"
      }
    }
  ]
}
 * 
 */